export const en = {
    products: "Products",
    product: "Product",
    qty: "QTY",
    price: "Price",
    remove: "Remove",
    add_to_cart: "Add to cart",
    show_more: "Show more",
    show_less: "Show less",

    order_summary: "Order summary",
    your_cart: "Your Cart",
    item: "item",
    items: "items",
    enter_discount_code: "Enter discount code",
    apply: "apply",
    continue_shopping: "Continue shopping",

    i_agree: "By proceeding, I agree that I have read and accept the",
    // privacy_policy: `<b>Privacy Policy, Refund Policy</b> and <b>Terms of Use</b>`,
    privacy_policy: "Privacy Policy",
    refund_policy: "Refund Policy",
    terms_of_use: "Terms of Use",
    and: " and ",
    total: "Total",
    exclude: "Excl.",
    include: "Incl.",
    tax: "Tax",
    subtotal: "Subtotal",
    discount: "Discount",
    checkout: "Checkout",
    final_calculation: `*All final calculations will be made at checkout.`,
}
