export const jp = {
    apply: "適用する",
    cart_is_empty: "カートは空です。カートに追加する商品を探しましょう",
    browse_products: "商品をブラウズする",
    invalid_coupon:
        "無効な割引コードが入力されました。コードを確認してもう一度試してください。",
    already_applied_coupon:
        "割引コード{{couponInputValue}}はすでに適用されています",
    products: "商品",
    product: "商品",
    qty: "数量",
    price: "価格",
    remove: "削除",
    add_to_cart: "カートに追加",
    show_more: "もっと見る",
    show_less: "少なく見る",
    order_summary: "注文概要",
    your_cart: "カート",
    item: "項目",
    items: "項目",
    enter_discount_code: "割引コードを入力",
    continue_shopping: "買い物を続ける",
    i_agree: "続けることにより、私は読んで理解し、承諾したことを認めます。",
    privacy_policy: "プライバシー・ポリシー",
    refund_policy: "返金ポリシー",
    terms_of_use: "利用規約",
    and: "そして",
    total: "合計",
    exclude: "除外",
    include: "含む",
    tax: "税",
    subtotal: "小計",
    discount: "割引",
    coupon_discount: "クーポン割引",
    checkout: "チェックアウト",
}
