export const ko = {
    apply: "적용",
    cart_is_empty: "카트가 비어 있습니다. 카트에 추가할 제품을 탐색하세요",
    browse_products: "제품 탐색",
    invalid_coupon:
        "잘못된 할인 코드를 입력했습니다. 코드를 확인하고 다시 시도하세요.",
    already_applied_coupon:
        "할인 코드 {{couponInputValue}}이(가) 이미 적용되었습니다",
    products: "제품",
    product: "제품",
    qty: "수량",
    price: "가격",
    remove: "제거",
    add_to_cart: "카트에 추가",
    show_more: "더 보기",
    show_less: "덜 보기",
    order_summary: "주문 요약",
    your_cart: "카트",
    item: "항목",
    items: "항목",
    enter_discount_code: "할인 코드 입력",
    continue_shopping: "쇼핑 계속",
    i_agree: "계속하면, 나는 읽었고 동의한다는 것을 인정합니다.",
    privacy_policy: "개인 정보 보호 정책",
    refund_policy: "환불 정책",
    terms_of_use: "이용 약관",
    and: "그리고",
    total: "총액",
    exclude: "제외",
    include: "포함",
    tax: "세금",
    subtotal: "소계",
    discount: "할인",
    coupon_discount: "쿠폰 할인",
    checkout: "체크아웃",
}
