export const getDefaultMocks = ()=> {
   return  {
       "id": "f67f73cb-7170-47cc-9091-70293391da81",
       "createdTime": "2023-02-28T06:46:39+00:00",
       "updatedTime": "2023-02-28T06:48:13+00:00",
       "discountAmount": 0,
       "cartAmount": 94780.19,
       "taxIncluded": false,
       "items": [
           {
               "quantity": 1,
               "imageUrl": "https://cdn11.bigcommerce.com/s-12tro8kxte/products/120/images/379/MicrosoftTeams-image_3__19536.1667493004.220.290.png?c=1",
               "salePrice": 1000.2,
               "totalSalePrice": 1000.2,
               "originalPrice": 1000.2,
               "totalOriginalPrice": 1000.2,
               "variantId": 85,
               "productId": 120,
               "name": "English 4 Skills Full Test",
               "shortDescription": "",
               "description": "<p><span style=\"font-size: 10pt;\">Get a personalized Barracuda English 4 Skills Full Test certificate and a Credly badge to add onto your LinkedIn profile</span></p>\n<p><span style=\"font-size: 14pt;\">Measures your English proficiency on the following skills:</span></p>\n<p><span style=\"font-size: 12pt;\"><span style=\"background-color: #ffcc00; padding: 2px 8px; border-radius: 12px;\">1</span> Speaking</span></p>\n<p><span style=\"font-size: 12pt;\"><span style=\"background-color: #ffcc00; padding: 2px 8px; border-radius: 12px;\">2</span> Listening</span></p>\n<p><span style=\"font-size: 12pt;\"><span style=\"background-color: #ffcc00; padding: 2px 8px; border-radius: 12px;\">3</span> Reading</span></p>\n<p><span style=\"font-size: 12pt;\"><span style=\"background-color: #ffcc00; padding: 2px 8px; border-radius: 12px;\">4</span> Writing</span></p>",
               "id": "b959b30a-b2bd-4b7e-b7fc-6e8906f69305",
               "sku": "",
               "minPurchaseQuantity": 1,
               "maxPurchaseQuantity": 1,
               "type": 0
           },
           {
               "quantity": 1,
               "imageUrl": "https://cdn11.bigcommerce.com/s-12tro8kxte/products/119/images/378/Property_1Reading_and_writing__88467.1667492698.220.290.png?c=1",
               "salePrice": 29.99,
               "totalSalePrice": 29.99,
               "originalPrice": 29.99,
               "totalOriginalPrice": 29.99,
               "variantId": 84,
               "productId": 119,
               "name": "Reading + Writing Module",
               "shortDescription": "",
               "description": "<p><span style=\"font-size: 14pt;\">Measures your English proficiency on the following skills:</span></p>\n<p><span style=\"font-size: 12pt;\"><span style=\"background-color: #ffcc00; padding: 2px 8px; border-radius: 12px;\">1</span> Reading</span></p>\n<p><span style=\"font-size: 12pt;\"><span style=\"background-color: #ffcc00; padding: 2px 8px; border-radius: 12px;\">2</span> Writing</span></p>",
               "id": "25c01967-ddd7-4214-b1b6-b765d8f4da03",
               "sku": "",
               "minPurchaseQuantity": 1,
               "maxPurchaseQuantity": 3,
               "type": 0
           },
           {
               "quantity": 1,
               "imageUrl": "https://cdn11.bigcommerce.com/r-4b20dad619e29ebf3490f7f35369a8220637ce48/themes/ClassicNext/images/ProductDefault.gif",
               "salePrice": 62500,
               "totalSalePrice": 62500,
               "originalPrice": 62500,
               "totalOriginalPrice": 62500,
               "variantId": 103,
               "productId": 140,
               "name": "123456789 123456789 123456789 123456789 1234567 89gg",
               "shortDescription": "",
               "description": "<p><span style=\"font-size: 14pt;\">Measures your English proficiency on the following skills:</span></p>\n<p><span style=\"font-size: 12pt;\"><span style=\"background-color: #ffcc00; padding: 2px 8px; border-radius: 12px;\">1</span> Reading</span></p>\n<p><span style=\"font-size: 12pt;\"><span style=\"background-color: #ffcc00; padding: 2px 8px; border-radius: 12px;\">2</span> Writing</span></p>",
               "id": "33f2dbdb-14d6-4afd-acea-cd823d0a0b78",
               "sku": "",
               "minPurchaseQuantity": 1,
               "maxPurchaseQuantity": 3,
               "type": 1
           }
       ],
       "locale": "en-US",
       "coupons": [],
       "baseAmount": 63530.19,
       "preTaxCartAmount": 63530.19,
       "currency": {
           "isoCode": null,
           "currencyCode": "EUR",
           "symbol": "€",
           "symbolPosition": 0,
           "decimalToken": ".",
           "thousandsToken": "/",
           "decimalPlaces": 2
       },
       "email": "ddd.ddd@ddd.ddd"
   }
}